language: python
matrix:
  include:
    - python: 2.7
      dist: bionic
    - python: 3.4
      dist: xenial
    - python: 3.5
      dist: bionic
    - python: 3.6
      dist: bionic
    - python: 3.7
      dist: bionic
    - python: 3.8
      dist: bionic
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - gfortran
    - libhdf5-dev
install:
- ( cd libcdf && make build && sudo make install )
- ( cd qdipole && ./configure && make build && sudo make install )
- pip install scipy
- pip install ./eoxmagmod/
script:
- pip list
- mkdir -p ./test && cd ./test
- pip show -f eoxmagmod
- python -c 'import eoxmagmod' && python -m unittest discover -p '[a-z]*.py' -v eoxmagmod
notifications:
  slack:
    secure: cbb7/6s0sglh2q7Lqnlq1I3tF8v2PS3KC+8ppjFFsKGzXWVImTSVU8md06Kkw1Hrf+mXm39x78NQx0o66EzMjZ2GS7SKD3eT3GDRqaF9COrc5zfeshZGF7swu/wtZMMMj0UrTxQnhJx09nwsTWGpCnCyEWOs0tHg+gUzoHqmM+E=
